name: hicom_patners
description: "Hicom Partner"

publish_to: 'none'



version: 1.0.6+10

environment:
  sdk: '>=3.4.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.2
  get_storage: ^2.1.1
  pull_to_refresh_flutter3: ^2.0.2
  flutter_tabler_icons: ^1.26.0
  country_picker: ^2.0.25
  intl_phone_field: ^3.2.0
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.0
  fading_edge_scrollview: ^4.1.1
  flutter_rating_bar: ^4.0.1
  enefty_icons: ^1.0.7
  url_launcher: ^6.2.6
  flutter_html: ^3.0.0-beta.2
  convex_bottom_bar: ^3.2.0
  intl: ^0.18.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  photo_view: ^0.15.0
  skeletonizer: ^2.1.0+1
  local_auth: ^2.3.0
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.0
  badges: ^3.1.2
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^19.3.0
  icons_launcher: ^3.0.0
  change_app_package_name: ^1.4.0
  disposable_cached_images: ^1.2.1
  flutter_native_splash: ^2.4.3
  iconsax_flutter: ^1.0.1
  flutter_lucide: ^1.6.2
  mobile_scanner: ^7.0.1
  flutter_multi_formatter: ^2.13.10
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  flutter_map_animations: ^0.9.0
  permission_handler: ^12.0.1
  latlong2: ^0.9.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0


icons_launcher:
  image_path: "assets/images/appIcon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg_assets/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/code-next-book.ttf